services:
  watcher:
    image: ghcr.io/jul-fls/arkea-arena-watcher:latest
    container_name: arkea-arena-watcher
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - watcher-data:/data
    environment:
      STATE_FILE: /data/state.json
      SESSION_FILE: /data/session.json
      PRESENTATION_URL: https://www.arkeaarena.com/evenements/electric-callboy-en-concert-30-janvier-2027-billetterie-bordeaux
      DISCORD_NOTIFY_ON_START: 1
      POLL_SECONDS: 5
      DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/<webhook_id>/<webhook_token>

volumes:
  watcher-data:
